CREATE TABLE tb_telephone (
                              id bigint GENERATED BY DEFAULT AS identity,
                              ddd text not null,
                              number text not null,

                            primary key (id)
);