CREATE TABLE tb_maintainer (
                                    id bigint GENERATED BY DEFAULT AS identity,
                                    name text not null,
                                    account_id bigint,
                                    telephone_id bigint,

                                    PRIMARY KEY (id)
)